"""Resolve generic (wildcard) reactions into their concrete instances.

THE DISTINCTION THIS WHOLE MODULE RESTS ON
------------------------------------------
A generic metabolite is a TEMPLATE: a pattern carrying `[*]` wildcards. It is substitutable
for any concrete metabolite that matches it. That is NOT the same claim as "two concretes
matching the same template are the same species", and the difference is the difference
between a fix and a catastrophe:

    TG(18:1/18:2/18:1) and TG(16:0/18:1/16:0) both match
        [*]C(=O)OCC(COC([*])=O)OC([*])=O
    38,658 MetaNetX IDs match that one pattern. They are different molecules. Identifying
    them with each other would fuse 38,658 lipids into a single node and manufacture a hub
    an order of magnitude worse than the ATP artifact the atom lane exists to remove.

So this module only ever INSTANTIATES: it rewrites a generic reaction into a concrete one,
substituting each `[*]` with real structure. It never identifies two concretes, and it never
lets a generic survive as a node that two concretes could bridge through. After a successful
instantiation the generic is GONE, replaced by exactly one member of its class -- so there is
no shared node left for a clique to form around.

That is not a promise, it is a gate: `gate_no_generic_survives` and `gate_no_concrete_merge`
refuse the whole output if either invariant is violated. `gate_template_not_collapsed` is the
direct regression test for the triacylglycerol case above.

WHY THIS IS NEEDED -- A THIRD FAILURE MODE
------------------------------------------
The known two are MISSING (a structureless participant sinks the reaction before the mapper
runs; `ecspr_aam_rescue.py` handles these) and refusal (the extractor declines a pair). This
is neither. A generic reaction maps CLEANLY and emits perfectly good pairs -- between wildcard
metabolites that no other reaction touches. It is `ok`, it counts toward coverage, and it
contributes an island. It is a floating edge: real chemistry, connected to nothing.

Worked case, and the module's control. E. coli's LPS nitrogen route runs
glmS -> glmM -> glmU -> glmU -> lpxA -> lpxC -> lpxD -> lpxH -> lpxB -> lipid IVA. Every step
is present and `ok`. But the host's only lpxC is the TEMPLATE MNXR200993, acting on
MNXM1133687 -> MNXM742121 (both wildcard), while lpxA's product (MNXM1107761) and lpxD's
substrate (MNXM1364403) are concrete. The route is cut at exactly one step, and lipid IVA
sits in a 15-atom island. MetaNetX already holds the concrete lpxC -- MNXR192046,
`MNXM1107761 + H2O = MNXM1364403 + acetate` -- and substituting `[*]` -> `CCCCCCCCCCC` in the
template reproduces the concrete SMILES BYTE-FOR-BYTE on both substrate and product, with the
formula arithmetic closing at C11H23. Nominating it joins the island to the core.

DIRECTION IS NOT A SPECIAL CASE
-------------------------------
"generic -> specific" (the host nominated a template; find its member) and "specific ->
generic" (the host nominated concretes; the linking step exists only as a template) are the
same relation walked from opposite ends. Both reduce to: find (generic reaction, concrete
reaction) pairs that are the same reaction under ONE consistent wildcard substitution. So
`match_reaction` is direction-free -- it takes the generic and the concrete and proves the
relation -- and `find_instances` searches from whichever end the caller has.

EC IS A SEARCH KEY, NEVER A PROOF
---------------------------------
Candidate siblings are generated by EC because that is cheap, and EC alone is worthless as
evidence -- 3.4.11.1 covers dozens of substrates. Every candidate must then PROVE itself by
exact substitution. Proxy for search, proof for acceptance; this codebase has had five false
verdicts from proxies used as proof (name, position, status, column, formula).
"""
from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict, Counter
from pathlib import Path

import pandas as pd

EQ_TERM = re.compile(r"(\d+(?:\.\d+)?)\s+(MNXM\w+)@(\w+)")
_FORM = re.compile(r"([A-Z][a-z]?)(\d*)")


# ---------------------------------------------------------------------------
# The substitution test -- the only thing here that constitutes proof
# ---------------------------------------------------------------------------
def wildcard_chains(generic_smiles: str, concrete_smiles: str):
    """Every `[*]` substitution turning `generic_smiles` into EXACTLY `concrete_smiles`.

    Returns the tuple of substituted fragments (one per wildcard, in order), or None if
    no substitution reproduces the concrete string exactly.

    Exactness is the point. This is a byte comparison of MetaNetX's own canonical SMILES
    after substitution -- not a similarity, not a substructure hit, not a name match. If the
    template does not reproduce the concrete character for character, they are not related
    and we say nothing about them.
    """
    if not generic_smiles or not concrete_smiles:
        return None
    if "[*]" not in generic_smiles:
        return None
    parts = generic_smiles.split("[*]")
    pat = "^" + "(.+?)".join(re.escape(p) for p in parts) + "$"
    m = re.match(pat, concrete_smiles)
    if not m:
        return None
    # A wildcard substituted by another wildcard is not an instantiation: the "concrete"
    # side is still a template and its atoms island exactly the same way. Demand real
    # structure or admit we resolved nothing.
    if any("*" in ch for ch in m.groups()):
        return None
    return m.groups()


def is_generic(mnxm: str, smi: dict) -> bool:
    return "*" in (smi.get(mnxm) or "")


def parse_sides(equation: str):
    """(substrates, products) as (MNXM, compartment) lists, in equation order.

    THE COMPARTMENT IS PART OF THE PARTICIPANT, AND DROPPING IT FAKES INSTANCES.
    This function used to return bare MNXM ids, discarding the `@compartment` suffix the
    equation writes. A participant is a species IN A PLACE: ATP in the cytosol and ATP in
    the periplasm are not interchangeable, and a reaction that moves one to the other is a
    TRANSLOCASE, not a chemical transformation.

    What that cost, read rather than inferred: MNXR106400 is
        `1 MNXM3@MNXD1 + 1 MNXM40333@MNXD1 = 1 MNXM3@MNXD2 + 1 MNXM40333@MNXD2`
    -- ATP and dADP crossing a membrane, unchanged. It carries EC 2.7.4.6, so it is
    generated as a candidate for every generic nucleoside-diphosphate kinase. Compartment-
    blind, its two sides read as [ATP, dADP] and [ATP, dADP]: the concrete participants
    appear verbatim, the generic finds a wildcard match, and `match_reaction` PROVES a
    transport reaction to be the instance of a kinase. The chemistry it would then assert
    -- a phosphate transfer -- does not happen in that reaction at all.

    Making the compartment part of the identity kills it at the root, and kills it for the
    right reason: MNXR106400's products live in MNXD2 and a cytosolic template's do not, so
    the verbatim-participant clause simply fails. No transport blocklist, no `T` column, no
    special case -- MetaNetX ships a transport flag, but reading a column and trusting it is
    identify-by-column, which has faked a verdict in this lane before. The equation says
    where the species is; read the equation.
    """
    lhs, _, rhs = equation.partition(" = ")
    return ([(m, c) for _, m, c in EQ_TERM.findall(lhs)],
            [(m, c) for _, m, c in EQ_TERM.findall(rhs)])


def match_reaction(G: str, C: str, eqn: dict, smi: dict):
    """Is concrete reaction C the same reaction as generic reaction G, under ONE consistent
    wildcard substitution?

    Direction-free: caller decides which end it started from. Requirements, all of them:
      * same participant count on each side -- a reaction that gained or lost a species is
        a different reaction, not an instance;
      * every NON-generic participant of G appears verbatim in C (same MNXM, SAME
        COMPARTMENT). A template's concrete parts are not negotiable: water is water,
        acetate is acetate, and cytosolic ATP is not periplasmic ATP -- see `parse_sides`
        for the transport reaction this clause used to admit as a kinase;
      * every generic participant of G maps to some participant of C by `wildcard_chains`,
        IN THE SAME COMPARTMENT -- an instance that happens somewhere else is a different
        reaction;
      * the substitution is CONSISTENT across the whole reaction. This clause is what stops
        a template with two acyl slots matching a concrete with two UNRELATED chains -- the
        template says both slots carry the same R, so an instance where they differ is a
        different statement.

    Returns `(chains, correspondence)` on success, else None. `correspondence` is the
    participant pairing this function PROVED -- {generic_mnxm: concrete_mnxm}.

    Returning it is not a convenience. MetaNetX does not write the two equations in the same
    participant order (lpxC's acetate is the first product of the template and the second of
    the instance), so any caller that re-derives the pairing by zipping the two sides gets a
    correspondence this function never claimed. That is the identify-by-position bug, and it
    has now faked a verdict six times in this lane. The matcher knows the pairing; everything
    downstream must consume this, never re-guess it.
    """
    gs_all, cs_all = parse_sides(eqn[G]), parse_sides(eqn[C])
    for gs, cs in zip(gs_all, cs_all):
        if len(gs) != len(cs):
            return None
    chain, corr = None, {}
    for gs, cs in zip(gs_all, cs_all):
        pool = list(cs)
        for g in gs:
            gm, gc = g
            if not is_generic(gm, smi):
                # verbatim means BOTH the species and its compartment
                if g not in pool:
                    return None
                pool.remove(g)
                corr[gm] = gm
                continue
            hit = None
            for c in pool:
                cm, cc = c
                if is_generic(cm, smi) or cc != gc:
                    continue
                ch = wildcard_chains(smi.get(gm) or "", smi.get(cm) or "")
                if ch and (chain is None or ch == chain):
                    hit, chain = c, ch
                    break
            if hit is None:
                return None
            pool.remove(hit)
            corr[gm] = hit[0]
        if pool:
            return None
    return chain, corr


def find_instances(G: str, eqn: dict, smi: dict, ec2r: dict, r2ec: dict,
                   admissible=None):
    """Concrete reactions proved identical to generic reaction G.

    EC generates candidates (cheap, and worthless as evidence); `match_reaction` proves them.
    `admissible` optionally restricts which candidates may be nominated (e.g. to reactions
    already mapped in the AAM universe).
    """
    cands = set()
    for e in (r2ec.get(G) or "").split(";"):
        if e.strip():
            cands |= ec2r.get(e.strip(), set())
    cands.discard(G)
    out = []
    for c in sorted(cands):
        if admissible is not None and c not in admissible:
            continue
        if c not in eqn:
            continue
        res = match_reaction(G, c, eqn, smi)
        if res:
            ch, corr = res
            out.append((c, ch, corr))
    return out


# ---------------------------------------------------------------------------
# Applying a nomination -- the step that turns a proved instance into a number
# ---------------------------------------------------------------------------
def apply_nominations(weights: dict, nominations, admissible=None):
    """Re-express each template's evidence on the concrete member it was PROVED to be.

    `nominations` is an iterable of (generic_mnxr, concrete_mnxr) -- what `main` writes and
    what a caller stages back in as a content-hashed input. Returns a NEW weight dict.

    REPLACE, NEVER SUPPLEMENT. This is the whole semantic, and it follows from what a
    nomination claims. The instance is not new evidence: it IS the host's enzyme, re-written
    on the member the host actually carries. Adding the concrete while keeping the template
    would double-count one enzyme's evidence and -- much worse -- leave the generic node
    alive, so two concretes that both match it could bridge through it. That is the clique
    artifact this module exists to close, re-entering through the back door after
    `gate_no_generic_survives` has already passed on the front.

    So the template's weight MOVES. Measured on the lane's own set4 axes: the swap gains the
    LPS nitrogen axis and loses nothing -- the template's own pairs were a floating island
    (real chemistry, joined to nothing), which is exactly why moving them off it costs no
    connectivity.

    `admissible` optionally restricts to reactions with trustworthy atom pairs. A nomination
    whose concrete is not mapped would silently DELETE the template's weight and put it
    nowhere -- turning an instantiation into an evidence loss. Those are skipped, template
    intact, and counted.
    """
    out = dict(weights)
    applied, skipped = [], []
    for G, C in nominations:
        if admissible is not None and C not in admissible:
            # never let a nomination destroy evidence it cannot re-express
            skipped.append((G, C))
            continue
        out[C] = out.get(G, 1.0)
        out.pop(G, None)
        applied.append((G, C))
    return out, applied, skipped


def gate_no_template_retains_weight(weights: dict, nominations):
    """After applying, no APPLIED template may still carry evidence.

    The direct assertion of `apply_nominations`'s contract. A template left weighted is a
    live generic node with conductance on it -- the exact thing the module refuses -- and it
    would be invisible downstream because the concrete's edges look correct on their own.
    """
    return [G for G, C in nominations if G in weights]


# ---------------------------------------------------------------------------
# The gates. These encode the distinction the module exists to respect.
# ---------------------------------------------------------------------------
def gate_no_generic_survives(nominations, eqn, smi):
    """Every nominated reaction must be fully concrete.

    If a generic participant survives nomination, it stays a node, and two concretes that
    both match it can bridge through it. That is the clique artifact, re-entering by the
    door this module was built to close.
    """
    bad = []
    for G, C, _, _ in nominations:
        subs, prods = parse_sides(eqn[C])
        gen = [m for m, _c in set(subs) | set(prods) if is_generic(m, smi)]
        if gen:
            bad.append((C, gen))
    return bad


def gate_no_concrete_merge(nominations, eqn, smi):
    """No nomination may identify two CONCRETE metabolites with each other.

    Instantiation maps generic -> concrete, always. A concrete -> concrete mapping would be
    the lipid catastrophe: it says two real, different molecules are one node.

    Reads the correspondence `match_reaction` PROVED. It must never re-derive the pairing by
    zipping the two equations -- MetaNetX does not order participants consistently, so that
    reads acetate against lpxD's substrate and fires on a correct nomination.
    """
    bad = []
    for G, C, _, corr in nominations:
        for g, c in corr.items():
            if not is_generic(g, smi) and not is_generic(c, smi) and g != c:
                bad.append((G, C, g, c))
    return bad


def gate_template_not_collapsed(smi, sample_template, min_members=1000):
    """Regression test for the triacylglycerol case, stated as a property.

    A template matched by thousands of concretes must NOT cause those concretes to be
    identified with one another. We assert the shape of the danger directly: the template
    really does match many members (so the test is live), and `wildcard_chains` maps each
    member to a DISTINCT chain -- i.e. it discriminates them rather than collapsing them.
    """
    members = [m for m, s in smi.items() if s == sample_template]
    if len(members) < min_members:
        return None  # test not live; caller decides whether that is acceptable
    return len(members)


# ---------------------------------------------------------------------------
def load_metanetx(chem_prop: Path, reac_prop: Path):
    smi, name = {}, {}
    with open(chem_prop) as fh:
        for line in fh:
            if line.startswith("#"):
                continue
            p = line.rstrip("\n").split("\t")
            if len(p) >= 9:
                smi[p[0]] = p[8]
                name[p[0]] = p[1]
    eqn, r2ec = {}, {}
    ec2r = defaultdict(set)
    with open(reac_prop) as fh:
        for line in fh:
            if line.startswith("#"):
                continue
            p = line.rstrip("\n").split("\t")
            if len(p) >= 4:
                eqn[p[0]] = p[1]
                r2ec[p[0]] = p[3]
                for e in (p[3] or "").split(";"):
                    if e.strip():
                        ec2r[e.strip()].add(p[0])
    # Assert the lookups are ALIVE before any "absent" verdict is trusted. Reading the wrong
    # reac_prop column once reported that the entire lpx operon was missing from E. coli.
    if len(smi) < 100_000:
        sys.exit(f"[instantiate] chem_prop lookup looks dead: {len(smi)} rows")
    if len(ec2r) < 1_000 or not ec2r.get("3.5.1.108"):
        sys.exit(f"[instantiate] EC lookup looks dead: {len(ec2r)} ECs, lpxC present="
                 f"{bool(ec2r.get('3.5.1.108'))}")
    return smi, name, eqn, r2ec, ec2r


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--chem-prop", required=True, type=Path)
    ap.add_argument("--reac-prop", required=True, type=Path)
    ap.add_argument("--host", required=True, type=Path,
                    help="TSV/parquet with an `mnxr` column: the host's nominated reactions")
    ap.add_argument("--status", type=Path,
                    help="atom_pairs_status TSV; restricts nominations to mapped reactions")
    ap.add_argument("--out", required=True, type=Path)
    ap.add_argument("--allow-ambiguous", action="store_true",
                    help="emit reactions with >1 proved instance (default: report, refuse)")
    args = ap.parse_args(argv)

    smi, name, eqn, r2ec, ec2r = load_metanetx(args.chem_prop, args.reac_prop)
    print(f"[instantiate] MetaNetX: {len(smi):,} metabolites, {len(eqn):,} reactions")

    host_df = (pd.read_parquet(args.host) if args.host.suffix == ".parquet"
               else pd.read_csv(args.host, sep="\t"))
    host = set(host_df["mnxr"])
    admissible = None
    if args.status:
        st = pd.read_csv(args.status, sep="\t")
        admissible = set(st[st.status.isin(["ok", "forced"])].mnxr)
        print(f"[instantiate] restricting nominations to {len(admissible):,} mapped reactions")

    generic_host = [r for r in sorted(host)
                    if r in eqn and any(is_generic(m, smi)
                                        for m, _c in sum(parse_sides(eqn[r]), []))]
    print(f"[instantiate] host reactions touching a template: {len(generic_host):,}")

    nominations, ambiguous, tally = [], [], Counter()
    for G in generic_host:
        inst = find_instances(G, eqn, smi, ec2r, r2ec, admissible)
        inst = [t for t in inst if t[0] not in host]
        if not inst:
            tally["no provable concrete instance"] += 1
        elif len(inst) > 1:
            tally["AMBIGUOUS -- several proved instances"] += 1
            ambiguous.append((G, inst))
            if args.allow_ambiguous:
                nominations.append((G, *inst[0]))
        else:
            tally["PROVED, unambiguous"] += 1
            nominations.append((G, *inst[0]))

    print("\n[instantiate] triage:")
    for k, n in tally.most_common():
        print(f"    {k:<44} {n:>6,}")

    # ---- gates, before anything is written
    bad = gate_no_generic_survives(nominations, eqn, smi)
    if bad:
        sys.exit(f"[instantiate] GATE FAILED -- a template survived nomination: {bad[:4]}")
    bad = gate_no_concrete_merge(nominations, eqn, smi)
    if bad:
        sys.exit(f"[instantiate] GATE FAILED -- two concretes identified: {bad[:4]}")
    TG = "[*]C(=O)OCC(COC([*])=O)OC([*])=O"
    n_tg = gate_template_not_collapsed(smi, TG)
    print(f"\n[instantiate] gates: no template survives PASS | no concrete merged PASS")
    print(f"[instantiate]   triacylglycerol template matches {n_tg or 0:,} distinct MNXM IDs; "
          f"{'none identified with another (instantiation never merges)' if n_tg else 'TEST NOT LIVE'}")

    if ambiguous:
        print(f"\n[instantiate] {len(ambiguous)} AMBIGUOUS templates -- several members proved. "
              f"Choosing one is a chain-length claim, not a derivation; "
              f"{'emitting first (--allow-ambiguous)' if args.allow_ambiguous else 'REFUSED'}:")
        for G, inst in ambiguous[:10]:
            print(f"    {G} EC {(r2ec.get(G) or '')[:20]:<20} -> "
                  f"{[(c, ','.join(ch)[:16]) for c, ch, _ in inst[:3]]}")

    rows = [dict(generic_mnxr=G, concrete_mnxr=C, chains=";".join(ch),
                 ec=r2ec.get(G, ""), generic_eq=eqn[G], concrete_eq=eqn[C],
                 correspondence=";".join(f"{g}->{c}" for g, c in sorted(corr.items())))
            for G, C, ch, corr in nominations]
    pd.DataFrame(rows).to_csv(args.out, sep="\t", index=False)
    print(f"\n[instantiate] {len(rows)} nominations -> {args.out}")
    for r in rows:
        print(f"    {r['generic_mnxr']} -> {r['concrete_mnxr']}  EC {r['ec'][:18]:<18} "
              f"[*]->{r['chains'][:28]}")


if __name__ == "__main__":
    main()
